package objectives

import (
	"github.com/arphillips06/TI4-stats/models"
)

var Secret = []models.Objective{
	{
		Name:        "Destroy Their Greatest Ship",
		Type:        "Secret",
		Points:      1,
		Description: "Destroy another player's war sun or flagship.",
		Phase:       "action",
	},
	{
		Name:        "Make an Example of Their World",
		Type:        "Secret",
		Points:      1,
		Description: "Destroy the last of a player's ground forces on a planet during the bombardment step.",
		Phase:       "action",
	},
	{
		Name:        "Spark a Rebellion",
		Type:        "Secret",
		Points:      1,
		Description: "Win a combat against a player who has the most victory points.",
		Phase:       "action",
	},
	{
		Name:        "Turn Their Fleets to Dust",
		Type:        "Secret",
		Points:      1,
		Description: "Destroy the last of a player's non-fighter ships in the active system during the space cannon offense step.",
		Phase:       "action",
	},
	{
		Name:        "Unveil Flagship",
		Type:        "Secret",
		Points:      1,
		Description: "Win a space combat in a system that contains your flagship. You cannot score this objective if your flagship is destroyed in the combat.",
		Phase:       "action",
	},
	{
		Name:        "Become a Martyr",
		Type:        "Secret",
		Points:      1,
		Description: "Lose control of a planet in a home system.",
		Phase:       "action",
	},
	{
		Name:        "Betray a Friend",
		Type:        "Secret",
		Points:      1,
		Description: "Win a combat against a player whose promissory note you had in your play area at the start of your tactical action.",
		Phase:       "action",
	},
	{
		Name:        "Brave the Void",
		Type:        "Secret",
		Points:      1,
		Description: "Win a combat in an anomaly.",
		Phase:       "action",
	},
	{
		Name:        "Darken the Skies",
		Type:        "Secret",
		Points:      1,
		Description: "Win a combat in another player's home system.",
		Phase:       "action",
	},
	{
		Name:        "Demonstrate Your Power",
		Type:        "Secret",
		Points:      1,
		Description: "Have 3 or more non-fighter ships in the active system at the end of a space combat.",
		Phase:       "action",
	},
	{
		Name:        "Fight With Precision",
		Type:        "Secret",
		Points:      1,
		Description: "Destroy the last of a player's fighters in the active system during the anti-fighter barrage step.",
		Phase:       "action",
	},
	{
		Name:        "Prove Endurance",
		Type:        "Secret",
		Points:      1,
		Description: "Be the last player to pass during a game round.",
		Phase:       "action",
	},
	{
		Name:        "Adapt New Strategies",
		Type:        "Secret",
		Points:      1,
		Description: "Own 2 faction technologies. (Valefar Assimilator technologies do not count toward this objective.)",
		Phase:       "status",
	},
	{
		Name:        "Become the Gatekeeper",
		Type:        "Secret",
		Points:      1,
		Description: "Have 1 or more ships in a system that contains an alpha wormhole and 1 or more ships in a system that contains a beta wormhole.",
		Phase:       "status",
	},
	{
		Name:        "Control the Region",
		Type:        "Secret",
		Points:      1,
		Description: "Have 1 or more ships in 6 systems.",
		Phase:       "status",
	},
	{
		Name:        "Establish a Perimeter",
		Type:        "Secret",
		Points:      1,
		Description: "Have 4 PDS units on the game board.",
		Phase:       "status",
	},
	{
		Name:        "Forge an Alliance",
		Type:        "Secret",
		Points:      1,
		Description: "Control 4 cultural planets.",
		Phase:       "status",
	},
	{
		Name:        "Form a Spy Network",
		Type:        "Secret",
		Points:      1,
		Description: "Discard 5 Action Cards.",
		Phase:       "status",
	},
	{
		Name:        "Fuel the War Machine",
		Type:        "Secret",
		Points:      1,
		Description: "Have 3 space docks on the game board.",
		Phase:       "status",
	},
	{
		Name:        "Gather a Mighty Fleet",
		Type:        "Secret",
		Points:      1,
		Description: "Have 5 dreadnoughts on the game board.",
		Phase:       "status",
	},
	{
		Name:        "Learn the Secrets of the Cosmos",
		Type:        "Secret",
		Points:      1,
		Description: "Have 1 or more ships in 3 systems that are each adjacent to an anomaly.",
		Phase:       "status",
	},
	{
		Name:        "Master the Laws of Physics",
		Type:        "Secret",
		Points:      1,
		Description: "Own 4 technologies of the same color.",
		Phase:       "status",
	},
	{
		Name:        "Mine Rare Metals",
		Type:        "Secret",
		Points:      1,
		Description: "Control 4 hazardous planets.",
		Phase:       "status",
	},
	{
		Name:        "Monopolize Production",
		Type:        "Secret",
		Points:      1,
		Description: "Control 4 industrial planets.",
		Phase:       "status",
	},
	{
		Name:        "Occupy the Seat of the Empire",
		Type:        "Secret",
		Points:      1,
		Description: "Control Mecatol Rex and have 3 or more ships in its system.",
		Phase:       "status",
	},
	{
		Name:        "Threaten Enemies",
		Type:        "Secret",
		Points:      1,
		Description: "Have 1 or more ships in a system that is adjacent to another player's home system.",
		Phase:       "status",
	},
	{
		Name:        "Defy Space and Time",
		Type:        "Secret",
		Points:      1,
		Description: "Have units in the wormhole nexus.",
		Phase:       "status",
	},
	{
		Name:        "Destroy Heretical Works",
		Type:        "Secret",
		Points:      1,
		Description: "Purge 2 of your relic fragments of any type.",
		Phase:       "status",
	},
	{
		Name:        "Establish Hegemony",
		Type:        "Secret",
		Points:      1,
		Description: "Control planets that have a combined influence value of at least 12.",
		Phase:       "status",
	},
	{
		Name:        "Foster Cohesion",
		Type:        "Secret",
		Points:      1,
		Description: "Be neighbors with all other players.",
		Phase:       "status",
	},
	{
		Name:        "Hoard Raw Materials",
		Type:        "Secret",
		Points:      1,
		Description: "Control planets that have a combined resource value of at least 12.",
		Phase:       "status",
	},
	{
		Name:        "Mechanize The Military",
		Type:        "Secret",
		Points:      1,
		Description: "Have 1 mech on each of 4 planets.",
		Phase:       "status",
	},
	{
		Name:        "Occupy The Fringe",
		Type:        "Secret",
		Points:      1,
		Description: "Have 9 or more ground forces on a planet that does not contain 1 of your space docks.",
		Phase:       "status",
	},
	{
		Name:        "Produce En Masse",
		Type:        "Secret",
		Points:      1,
		Description: "Have units with a combined PRODUCTION value of at least 8 in a single system.",
		Phase:       "status",
	},
	{
		Name:        "Seize An Icon",
		Type:        "Secret",
		Points:      1,
		Description: "Control a legendary planet.",
		Phase:       "status",
	},
	{
		Name:        "Stake your Claim",
		Type:        "Secret",
		Points:      1,
		Description: "Control a planet in a system that contains a planet controlled by another player.",
		Phase:       "status",
	},
	{
		Name:        "Strengthen Bonds",
		Type:        "Secret",
		Points:      1,
		Description: "Have another player's promissory note in your play area.",
		Phase:       "status",
	},
	{
		Name:        "Dictate Policy",
		Type:        "Secret",
		Points:      1,
		Description: "There are 3 or more laws in play.",
		Phase:       "agenda",
	},
	{
		Name:        "Drive the Debate",
		Type:        "Secret",
		Points:      1,
		Description: "You or a planet you control are elected by an agenda.",
		Phase:       "agenda",
	},
}
